### ISSUE TITLE
Module not found: Error: Can't resolve 'url' error with create-react-app/webpack 5

### ISSUE THREAD

**Issue by sw-yx** [anttiviljami/openapi-client-axios#116] opened 2022-05-18 03:47 UTC
I suspect this error is similar to #38  but there is not documented solution:

```
✘ itaydonanhirsh@purr  ~/src/autokitteh/web/dashboard   main  npm run build                   (/Users/itaydonanhirsh/.kube/config doesn't exist)

> dashboard@0.1.0 build
> react-scripts build

Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve 'url' in '/Users/itaydonanhirsh/src/autokitteh/web/dashboard/node_modules/@apidevtools/json-schema-ref-parser/lib/util'
Did you mean './url'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (node_modules, /Users/itaydonanhirsh/src/autokitteh/web/dashboard/node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
        - install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "url": false }
```

**Comment by EthanBowenSlalom** [comment] 2022-06-03 16:24
Bump.  Same here.  Also affecting:  https://github.com/anttiviljami/react-openapi-client

**Comment by sw-yx** [comment] 2022-06-10 12:36
i ended up using react app rewired to polyfill the url module. not a great solution but good enough

**Comment by anttiviljami** [comment] 2022-06-10 13:00
Thanks for sharing the solution @sw-yx!

Seems the issue is with `@apidevtools/json-schema-ref-parser` module depending on the `url` module, which is not polyfilled by default on webpack 5 anymore.

https://github.com/APIDevTools/json-schema-ref-parser/blob/main/lib/util/url.js#L25

Looks like someone already reported this upstream but the issue was closed with workarounds. Author seems to be open for PRs. 

Would be glad to uprade the ref parse to a browser compatible version if someone finds a way to get rid of the Node.js dependencies 👍

https://github.com/APIDevTools/json-schema-ref-parser/issues/129

**Comment by javialon26** [comment] 2022-06-21 22:15
@anttiviljami @sw-yx Hi, I'm trying to add polyfills to create-react-app (react-scripts 5.0.1) but I'm getting an error with copy-anything module:

```
TypeError: (0 , copy_anything_1.copy) is not a function
    at OpenAPIClientAxios.<anonymous> (client.js:330:1)
    at step (client.js:142:1)
    at Object.next (client.js:73:1)
    at fulfilled (client.js:27:1)
```

I installed react-app-rewired (v^2.2.1) and this is my config overrides:

```
const webpack = require('webpack');

module.exports = function override(config) {
  const fallback = config.resolve.fallback || {};

  Object.assign(fallback, {
    http: require.resolve("stream-http"),
    https: require.resolve("https-browserify"),
    url: require.resolve('url'),
  });

  config.resolve.fallback = fallback;
  config.plugins = (config.plugins || []).concat([
    new webpack.ProvidePlugin({
      process: 'process/browser.js',
      Buffer: ['buffer', 'Buffer'] 
    }),
  ]);

  return config;
};
```

**Comment by sscots** [comment] 2022-06-27 14:25
+1

**Comment by javialon26** [comment] 2022-07-13 13:12
@nathanmargaglio Yes, we use a workaround for now.

This is the react-app-rewired final config:

```
const webpack = require('webpack');

module.exports = function override(config) {
  const fallback = config.resolve.fallback || {};

  Object.assign(fallback, {
    https: require.resolve('https-browserify'),
    http: require.resolve('stream-http'),
    util: require.resolve('util/'),
    url: require.resolve('url/'),
  });

  config.resolve.fallback = fallback;
  config.plugins = (config.plugins || []).concat([
    new webpack.ProvidePlugin({
      process: 'process/browser.js',
      Buffer: ['buffer', 'Buffer'],
    }),
  ]);

  return config;
};
```

And we must activate the quick: true option in OpenAPIClientAxios in order to bypass the execution of copy-anything. See this: https://github.com/anttiviljami/openapi-client-axios/blob/master/packages/openapi-client-axios/src/client.ts#L145

**Comment by anttiviljami** [comment] 2023-01-14 10:15
This issue should be fixed with `openapi-client-axios@6.1.0`

**Closed by anttiviljami** 2023-01-14 10:15 UTC
Labels: bug

**Comment by albiorixUA** [comment] 2023-05-17 12:27
I have this issue in v.7.1.3

**Comment by anttiviljami** [comment] 2023-05-28 11:36
Hi @albiorixUA, just tested this both with vite and CRA, both bundling fine without any extra steps needed. Can you describe your setup where this didn't work?
